name: Metrics
on:
  # Agenda a atualização para as 00:00 UTC diariamente
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente se quiser testar agora
  workflow_dispatch:
  # Roda sempre que fizer push na master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Configurações do Utilizador
          user: francissantiago
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          # Visual (Dark Mode para combinar com Web3)
          config_display: large
          
          # Plugin: Linguagens (As suas ferramentas)
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: lines, percentage
          
          # Plugin: Linhas de Código (Mostra volume de trabalho)
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
